### ISSUE TITLE
Unfold command?

### ISSUE THREAD

**Issue by Fred-Vatin** [dakaraphi/vscode-extension-fold#1]
Hi,

Great extension. What about the same commands to unfold?

I guess it is related to this [issue ](https://github.com/Microsoft/vscode/issues/22276)

**Comment by d-akara** [comment]
I've never had a need for specific unfold.  I generally unfold all and then issue the type of folding I want.
At least for me, I think doubling up all the commands with unfold versions would probably not speed up my workflow, but I would be interested in how you envision the use of such commands.

**Comment by Fred-Vatin** [comment]
You're right. I can use the same workflow as you and get used to it. 👍
