### ISSUE TITLE
Support folding beyond 7 levels

### ISSUE THREAD

**Issue by aaroncrawford** [dakaraphi/vscode-extension-fold#11]
Not sure if this is due to a new vscode version or not, but I cannot consistently get the Folding at Cursor level to work.  See this GIF:

In the gif, I'm using the Fold Plus: All at Same Level as Cursor.  I think it's suppose to fold the rest of the li's, right?

I've tried toggling the fold indentation/language to no avail.

Can you reproduce this?

Thanks

**Comment by d-akara** [comment]
It seems to still be working for me.  Would you be able to attach a small snippet that exposes the problem so I can try it with the same data?

**Comment by aaroncrawford** [comment]
Sure thing, here's the file :

https://d.pr/n/INLq1c

Try it at line 252, for example.  Mine just folds the current line, but none of the others at that level.

If it's useful, I'm using tab indentation with 4 spaces in VSC.

**Comment by d-akara** [comment]
ok, I figured out the issue.  The fold at cursor level command uses VSCodes underlying fold level commands.  Unfortunately, VSCode only supports 7 levels and this is deeper than 7 levels.

I will look to see if I can manually add that in the future for levels deeper than 7.  It might not be efficient on a large file, but I might can make it work.

**Comment by aaroncrawford** [comment]
Great, thank you for looking.  Some of these larger React files continually zip past the 7 levels.

**Comment by d-akara** [comment]
@aaroncrawford just published a new version that should now support unlimited depth.
Let me know if this works for you.

**Comment by aaroncrawford** [comment]
Thank you!  Works great! @dakaraphi
