### ISSUE TITLE
"All with Selected Text" Options Fails for Some Selections

### ISSUE THREAD

**Issue by thelaughingwolf** [dakaraphi/vscode-extension-fold#13]
This extension looks fantastic. I grabbed it to help me fold an unwieldy Mocha test file, hoping to fold every `it( . . . )` method. Wanting to avoid folding lines with `await`, strings with `it` in them, etc., I selected `it(` and chose **All with Selected Text**. That popped up an error in the corner:

Command 'Fold Plus: All with Selected Text' resulted in an error (Running the contributed command: 'dakara-foldplus.selection' failed.)

I discovered I could instead select the tab before `it` and leave the parenthesis out, which successfully folded only the lines I wanted to fold. I'm guessing there's some RegEx going on?

**Comment by d-akara** [comment]
Ahh yes, you are correct.  This gets passed to a regex function.  I will try to get a fix soon.  Thanks

**Comment by d-akara** [comment]
@thelaughingwolf fix published to marketplace.  Let me know if you have any issues.
