### ISSUE TITLE
Provide feature which allows target of fold to be different than context to determine fold

### ISSUE THREAD

**Issue by Fred-Vatin** [dakaraphi/vscode-extension-fold#2]
VS Code version | OS | Extension version
------------------ | ---- | ----
1.13.0  | Win x64 pro (french) | 1.1.0

## Steps to reproduce

1. json code sample:

```
[
  {
    "key": "value1"
  },
  {
    "key": "value2"
  },
  {
    "key": "value3"
  }
]
```

2. 
   - a) Select for instance one of the `key`
or
   - b) Put the caret into one of the block, e.g. at a `:`

3. 
   - a) Run `dakara-foldplus.selection` command
or
   - b) Run `dakara-foldplus.levelAtCursor` command

## Expectation

- a) Fold all blocks that contains the selected text
- b) Fold all blocks that are at the same level as cursor

## Results

Nothing happens

## Current working implementation

It will work if:

- a) you select one of the `{`
- b) you put the caret just before or just after a `{` or a `}`

**Comment by d-akara** [comment]
The subject of vscode fold commands is typically the line to fold.
I think what you are expecting is to fold on the parent.

**Comment by Fred-Vatin** [comment]
In that case, yes.

**Comment by d-akara** [comment]
Added new commands including `Fold All Same Level as Parent`
https://github.com/dakaraphi/vscode-extension-fold/commit/5ea76679a4e56ecc24bc82759cd2bff50bea7db6
