### ISSUE TITLE
Toggle current fold

### ISSUE THREAD

**Issue by ricobl** [dakaraphi/vscode-extension-fold#8]
Looks like some people (including me) are interested in toggling the current fold level: https://github.com/Microsoft/vscode/issues/18549

Any intention of implementing this?

I've also noticed a closed issue for unfolding (https://github.com/dakaraphi/vscode-extension-fold/issues/1). Toggling could resolve this too.

**Comment by d-akara** [comment]
vscode has now implemented this in microsoft/vscode#18549

**Comment by ricobl** [comment]
Cool, I'll wait for the release! Thanks for posting back here @dakaraphi!
