### ISSUE TITLE
"All with selected text" has stopped working 

### ISSUE THREAD

**Issue by csprocket777** [dakaraphi/vscode-extension-fold#9]
I'm using VSCode 1.31.0 with Fold Plus 1.3.1 and when I select some text in a JSON file, and try "Fold Plus: All with selected text", I visually see the collapse happen but then it immediately opens right back up and doesn't stick.

if there's only one entry in the file with that selected text, it collapses that entry. But if there's more than one instance of that selected text, the text collapse flickers and then re-opens.

**Comment by d-akara** [comment]
Yuck, just tried it.  Looks like several commands are broken :-(
Will take a look as soon as I can.
Thanks

**Comment by csprocket777** [comment]
Awesome, thank you! I've come to rely on this feature! :)

**Comment by csprocket777** [comment]
I can't tell you how much I miss having this feature. Anxiously awaiting a fix.

**Comment by d-akara** [comment]
@csprocket777 new version is now published.  I had to restart vscode before it worked.
Looks like I may need to do something to make the changes apply with their new hot replace.  I will have to look at that later.

Changes for vscode 1.31 compatibility 3c4cdb794dfbee6b7efb9968d536f139284238f9

**Comment by csprocket777** [comment]
I have updated and restarted VSCode and it's still not working.

**Comment by d-akara** [comment]
@csprocket777  Could you paste a small sample snippet of JSON that exhibits the problem.
Let me know where you have the cursor when you execute the command.

**Comment by csprocket777** [comment]
Sure.

```
{
    "theme": "light",
    "meta":
    {
        "colorizationInfoModal":
        {
            "enabled": "true",
            "largeModal": "true",
            "title":
            {
                "text": "Colorization",
                "classNames": "extraLight"
            },
            "body": [
            {
                "text": "The colorization filter changes the color of the people or connections to highlight clusters and help identify patterns. By default, both the people within the network map and their connections are colored by organizational team membership.",
                "classNames": "lead extraLight"
            },
            {
                "text": "Coloring the connections will highlight those relationships which carry the chosen benefit.",
                "classNames": "extraLight"
            },
            {
                "text": "<ul><li><span class='bold'>Desired Access</span> highlights the connections that have indicated they <i>would benefit from greater access</i> to that person.</li><li><span class='bold'>Advice</span> highlights relationships that provide \"Career advice or other developmental feedback that helps me be more effective in my work.\"</li><li><span class='bold'>Decision</span> highlights relationships that provide \"Access to decision-makers and/or political support that allows me to move plans ahead.\"</li><li><span class='bold'>Energy</span> highlights relationships that are considered <i>a source of positive energy</i></li><li><span class='bold'>Information</span> highlights relationships that provide \"Information that helps me do my job\"</li><li><span class='bold'>Innovation</span> highlights relationships that provide \"Innovative ideas or perspectives that up-level my work or ideas\"</li><li><span class='bold'>Support</span> highlights relationships that provide \"Personal support and the ability to vent or discuss a tough work-related problem in ways that help me get back on track.\"</li><li><span class='bold'>Problem Solving</span> highlights relationships that provide \"Problem-solving interactions that actively challenge my thinking on problems or opportunities in my work.\"</li><li><span class='bold'>Purpose</span> highlights relationships that provide \"Purpose or a sense of what I do at work has a positive impact and matters.\"</li></ul>",
                "classNames": "extraLight"
            }]
        },
...
```

I'm selecting the text `"body"` and running the command. this the top of the file. I can see it iterating through all the instances of "body" in the document, collapsing them, but then the end result is they are still uncollapsed.

This structure is fairly deep so i tried to find an example that still exhibited the issue without putting the whole file here.

**Comment by d-akara** [comment]
I just opened an issue with VSCode.  Looks like the behavior of one of their API's has changed.
https://github.com/Microsoft/vscode/issues/69012

For now, you can work around this by manually selecting the word instead of just placing the cursor.

**Comment by csprocket777** [comment]
I'm selecting the word inside the quotes, should I be selecting the quotes as well?

**Comment by d-akara** [comment]
Just select the word.
However, there is one other issue I forgot to mention for the sample you posted.
As it is currently formatted above, those lines will not fold.  If you hover over them, there is no '-' symbol you can click on to fold them on the 'body' line
This is because the next line is the same indentation level.
If you do 'format document', you should then be able to fold them on the 'body' line

**Comment by csprocket777** [comment]
AWESOME!! Works! I forgot about the indent level. Thank you!
